## Pandas

In [4]:
import pandas as pd
import numpy as np

pd.__version__

'1.3.4'

In [3]:
pd?

## Pandas Series

In [5]:
data = pd.Series([11,22,33,44,55,66])
data

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [6]:
data.values

array([11, 22, 33, 44, 55, 66], dtype=int64)

In [7]:
data.index

RangeIndex(start=0, stop=6, step=1)

In [9]:
data[0]

11

In [13]:
data[2:]

c    33
d    44
e    55
f    66
dtype: int64

## Series as generalized numpy arrays

In [11]:
data = pd.Series([11,22,33,44,55,66],index=['a','b','c','d','e','f'])
data

a    11
b    22
c    33
d    44
e    55
f    66
dtype: int64

In [12]:
data['c']

33

## Series as specialized dictionary

In [14]:
population_dict = {
    'California':38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
population['California': 'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

## Pandas DataFrame Object

### Dataframe as a generalized Numpy Array

In [17]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
 'Florida': 170312, 'Illinois': 149995}
area_dict

{'California': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [18]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
states = pd.DataFrame({'population':population,
                      'area':area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [21]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

### Dataframe as specialized dictionary

In [22]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing Dataframe objects from Dictionary of Series

In [25]:
states = pd.DataFrame({'population':population,
                      'area':area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### Constructing Dataframe objects from list of Dicts

In [35]:
data = [{'a': i, 'b': 2 * i}for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

### From 2-D Numpy Array

In [36]:
pd.DataFrame(np.random.random((3,2)), columns=['foo','bar'],index =['a','b','c'])

        foo       bar
a  0.379283  0.377566
b  0.160275  0.515537
c  0.672534  0.903098